In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Import data
#### Import from drive

In [ ]:
paid_transaction = pd.read_excel('/content/drive/MyDrive/Data DS Bootcamp/Homework-DataFrame-Dataset.xlsx', sheet_name='Paid-Transaction')
print('paid_transaction data shape:', paid_transaction.shape)
paid_transaction.head(10)

paid_transaction data shape: (12000, 11)

,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
0,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0
1,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0
2,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0
3,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0
4,20170722,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0
5,20170714,201707149671962,fauzannor,andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,10400.0,9000,0.0
6,20170703,201707039018928,della,Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,2900.0,0,0.0
7,20170707,201707079291011,Sri,Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,5800.0,0,0.0
8,20170703,201706218386960,Irene,Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,10000.0,9000,0.0
9,20170724,201707230047939,tofani,Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,22500.0,10000,0.0

In [ ]:
seller = pd.read_excel('/content/drive/MyDrive/Data DS Bootcamp/Homework-DataFrame-Dataset.xlsx', sheet_name='Seller')
print('seller data shape:', seller.shape)
seller.head(10)

seller data shape: (12000, 2)

      Order Number        Seller
0  201707209929420  Global Phone
1  201707129550097        E-shop
2  201707039056021   twelven com
3  201707099376522      GRAMEDIA
4  201707028956707        E-Bold
5  201707240063113        E-Bold
6  201707209912804        E-Bold
7  201707209928094        E-Bold
8  201707109436194         Axora
9  201707219955273   Fordza shop

### **1. Menyisipkan kolom 'Full Name' setelah 'Last Name'**
#### Menggunakan .str.title() untuk mengkapitalisasi huruf pertama

In [ ]:
paid_transaction.insert(4, 'Full Name', (paid_transaction['First Name'].str.title() + ' ' + paid_transaction['Last Name'].str.title()))
paid_transaction.head(10)

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
0,20170724,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0
1,20170701,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0
2,20170707,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0
3,20170720,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0
4,20170722,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0
5,20170714,201707149671962,fauzannor,andri,Fauzannor Andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,10400.0,9000,0.0
6,20170703,201707039018928,della,Suryo,Della Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,2900.0,0,0.0
7,20170707,201707079291011,Sri,Oki,Sri Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,5800.0,0,0.0
8,20170703,201706218386960,Irene,Hana,Irene Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,10000.0,9000,0.0
9,20170724,201707230047939,tofani,Valentina,Tofani Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,22500.0,10000,0.0

### **2. Menyisipkan kolom 'GMV' setelah 'Seller Discount'**
#### Gross Merchandise Value (GMV) = transaction amount - seller discount + delivery fee

In [ ]:
paid_transaction.insert(9, 'GMV', (paid_transaction['Transaction Amount'] - paid_transaction['Seller Discount'] + paid_transaction['Delivery Fee']))
paid_transaction.head(10)

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount
0,20170724,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0
1,20170701,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0
2,20170707,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0
3,20170720,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0
4,20170722,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0
5,20170714,201707149671962,fauzannor,andri,Fauzannor Andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,158000,10400.0,9000,0.0
6,20170703,201707039018928,della,Suryo,Della Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,41900,2900.0,0,0.0
7,20170707,201707079291011,Sri,Oki,Sri Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,83800,5800.0,0,0.0
8,20170703,201706218386960,Irene,Hana,Irene Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,152600,10000.0,9000,0.0
9,20170724,201707230047939,tofani,Valentina,Tofani Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,333100,22500.0,10000,0.0

### **3. Pengelompokan 'Meta Category' menjadi 2 group dan membuat dataframe baru untuk menampilkan jumlah total GMV *bulanan* tiap group**
#### Group 1: Home/Food, Sport/Hobi/Otomotif, Fashion, Beauty/Health
#### Group 2: Gadget/ Komputer, Elektronik, Service/ Mokado, Babies/ Kids

In [ ]:
# Define group
group_1 = ['Home/Food', 'Sport/Hobi/Otomotif', 'Fashion', 'Beauty/Health']
group_2 = ['Gadget/ Komputer', 'Elektronik', 'Service/ Mokado', 'Babies/ Kids']

# Mapping menggunakan dictionary
category_map = {cat: 'Group 1' for cat in group_1}
category_map.update({cat: 'Group 2' for cat in group_2})

# Kolom baru 'Category' berisi pengelompokan berdasarkan nilai 'Meta Category'
paid_transaction['Category'] = paid_transaction['Meta Category'].map(category_map)
paid_transaction.head(10)

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Category
0,20170724,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0,Group 2
1,20170701,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,Group 2
2,20170707,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,Group 2
3,20170720,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Group 1
4,20170722,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Group 2
5,20170714,201707149671962,fauzannor,andri,Fauzannor Andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,158000,10400.0,9000,0.0,Group 2
6,20170703,201707039018928,della,Suryo,Della Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,41900,2900.0,0,0.0,Group 2
7,20170707,201707079291011,Sri,Oki,Sri Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,83800,5800.0,0,0.0,Group 2
8,20170703,201706218386960,Irene,Hana,Irene Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,152600,10000.0,9000,0.0,Group 2
9,20170724,201707230047939,tofani,Valentina,Tofani Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,333100,22500.0,10000,0.0,Group 1

In [ ]:
# Mengubah format 'Paid Date' dari 'yyyymmdd' menjadi 'yyyy/mm/dd'
paid_transaction['Paid Date'] = pd.to_datetime(paid_transaction['Paid Date'].astype(str), format='%Y%m%d')

# Menambahkan kolom 'Month'
paid_transaction['Month'] = paid_transaction['Paid Date'].dt.to_period('M')

In [ ]:
# Membuat dataframe pivot table
# Pengelompokan berdasar 'Category'
# Menjumlahkan GMV per bulan dari 'Paid Date'
category_pivot = paid_transaction.pivot_table(values='GMV', index='Month', columns='Category', aggfunc='sum').reset_index()
category_pivot

Category    Month    Group 1    Group 2
0         2017-07   31308700  230414100
1         2017-08   15787000  348790700
2         2017-09  129389200  191482700
3         2017-10   50245600  150263700
4         2017-11  144480300  326532200
5         2017-12   50632900  451421300

### **4. Python statement untuk mencari Seller yang memiliki total GMV tertinggi pada 2017/08**
#### Menggunakan fungsi sum()

In [ ]:
# Menggabungkan dataframe "paid_transaction" dan "seller" berdasarkan "order number"
paid_seller_merged = pd.merge(paid_transaction, seller, on='Order Number')
paid_seller_merged.head(10)

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Category,Month,Seller
0,2017-07-24,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0,Group 2,2017-07,Babymaniashop
1,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,Group 2,2017-07,E-Bold
2,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,Group 2,2017-07,XLmystore
3,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Group 1,2017-07,Ennwen Online Store
4,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Group 2,2017-07,Media Gadget
5,2017-07-14,201707149671962,fauzannor,andri,Fauzannor Andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,158000,10400.0,9000,0.0,Group 2,2017-07,E-Bold
6,2017-07-03,201707039018928,della,Suryo,Della Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,41900,2900.0,0,0.0,Group 2,2017-07,E-Bold
7,2017-07-07,201707079291011,Sri,Oki,Sri Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,83800,5800.0,0,0.0,Group 2,2017-07,E-Bold
8,2017-07-03,201706218386960,Irene,Hana,Irene Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,152600,10000.0,9000,0.0,Group 2,2017-07,Voucher Plus
9,2017-07-24,201707230047939,tofani,Valentina,Tofani Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,333100,22500.0,10000,0.0,Group 1,2017-07,CSA Shop

In [ ]:
# Mencari 'Seller' dengan 'GMV' tertinggi pada 2017/07
highest_gmv = paid_seller_merged.loc[paid_seller_merged['Month'] == '2017/07'].groupby('Seller')['GMV'].sum().idxmax()
print("Seller dengan GMV tertinggi pada Agustus 2017: " + highest_gmv)

Seller dengan GMV tertinggi pada Agustus 2017: E-Bold

### **5. Python statement untuk mencari Seller yang memiliki transaksi terbanyak pada 2017/09**
#### Menggunakan fungsi count()

In [ ]:
# Mencari 'Seller' dengan total transaksi terbanyak pada 2017/09
highest_volume = paid_seller_merged.loc[paid_seller_merged['Month'] == '2017/09'].groupby('Seller')['GMV'].count().idxmax()
print("Seller dengan transaksi terbanyak pada September 2017: " + highest_volume)

Seller dengan transaksi terbanyak pada September 2017: E-Bold

### *Penjelasan fungsi*
#### 1) `.loc[ ]` = Melakukan filter dengan boolean value (True/False) terhadap tahun/bulan yang dipilih
#### 2) `.groupby().sum()` atau `.groupby().count()` = Mengelompokkan dan melakukan operasi matematika
#### 3) `.idxmax()` = Mencari yang tertinggi